pipeline {
    agent any

    environment {
        //  test reports
        VENV = "venv"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'your-github-cred-id',
                    url: 'https://github.com/<username>/alx-backend-python.git'
            }
        }

        stage('Setup Python') {
            steps {
                sh """
                python3 -m venv ${VENV}
                . ${VENV}/bin/activate
                pip install --upgrade pip
                pip install -r messaging_app/requirements.txt
                """
            }
        }

        stage('Run Tests') {
            steps {
                sh """
                . ${VENV}/bin/activate
                pytest messaging_app/tests --junitxml=report.xml
                """
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }

    triggers {
        //
    }
}
